### PR TITLE
Fix for reading CutBookkeepers in full xAODs

### PR DESCRIPTION
**Pull request by mmilesi**
See #504 

@kkrizka , can you check everything is fine now? If there's no problem, please go ahead and merge.

### CODE REVIEW

**Comment by kkrizka** [comment]
Can we keep support for not using CutBookkepers? For some reason, some TRUTH1 DxAODs don't have this metadata. I can try to implement the correct non-CutBookkeepers sum of weights tonight.

**Comment by mmilesi** [comment]
Hi Karol,

In that case, why not simply reading the first bin of the cutflow and
cutflow weighted histograms?

Marco

**Comment by kkrizka** [comment]
It is what I am doing right now to get around the bad non-metadata sum of weight calculation. The problem is that the `BasicEventSelection` in this PR will crash when running over the TRUTH1 due to the missing CutBookkeepers. Maybe a good compromise would be to use `m_useMetaData` to disable to disable the CutBookkeepers and not include a non-metadata sum of weight calculation. What do you think?

**Comment by mmilesi** [comment]
Ah, I see.
In that case yes, let's have a protection for the whole CutBookkeepers
part, and use the cutflow in the other case.
Actually, I don't know if there's a way to get the right weights sum rather
than getting the weight event by event, which is what the cutflow
stores....maybe it's a PAThelp question.

Is it OK if I add the protection tomorrow?

Cheers
Marco

**Comment by mmilesi** [comment]
Hi @kkrizka ,

I managed to make the change now :wink: 

Feel free to edit if needed

**Comment by mmilesi** [comment]
Hi @kkrizka ,

any news on this? Can we merge, or are you doing some work still?

**Comment by kratsg** [comment]
retest this please

**Pull request merged**
