### PR TITLE
Bug fix for basicEventSel

### PR DESCRIPTION
**Pull request by johnda102**

### CODE REVIEW

**Comment by mmilesi** [comment]
Hi @johnda102 (and @kratsg ) ,

this is all good, thanks!

I am just wondering....didn't you get my previous commit on exactly the same issue working in your master? 

commit 5f9abf8ac59b3f99177c9b21c2b6abc14ee4d013
Author: Marco Milesi <marco.milesi@cern.ch>
Date:   Tue Jun 30 11:16:19 2015 +0000

Sometimes this git still puzzles me :confused:

**Comment by johnda102** [comment]
HI @mmilesi 

   No I didnt see it in master.  Was there a merge request that didnt get pulled ?

**Comment by mmilesi** [comment]
No, I just pushed directly to master (against all the rules :laughing:  ). That's probably why you didn't notice...

**Comment by kratsg** [comment]
@mmilesi :-1: :angry:

**Pull request merged**
