### PR TITLE
Adding common XSec handeling

### PR DESCRIPTION
**Pull request by johnda102**
Start loading common XSec files

### CODE REVIEW

**Comment by johnda102** [comment]
retry

**Comment by johnda102** [comment]
@xAH-bot  retry

**Comment by johnda102** [comment]
There is some problem with the bot.  
Seems like cvms is down whereever the bot is compiling.  
Works fine when I do it by hadn in the interactive nodes.

**Comment by kratsg** [comment]
retry

**Comment by kratsg** [comment]
@xAH-bot test again

**Comment by kratsg** [comment]
@xAH-bot test this please

**Pull request merged**
