### PR TITLE
Fix: algorithm registry

### LINKED ISSUE #366: countUsed() functionality broken
The base class has a registerClass function that is meant to keep track of how many instances of a class have been created.  

It seems this is not active.  Im creating multiple muonSelectors and I see this->countUsed() is always 0. 

Searching the c++ I never see AH::Algorithm::registerClass invoked (for any class). 

Has anyone used this functionality before ?  

It looks like 
ElectronSelector.cxx
MuonSelector.cxx
and 
TauSelector.cxx 

are accessing countUsed() function.

### PR DESCRIPTION
**Pull request by kratsg**
This will close #366 . @johnda102 will need to confirm that it works.

This is a potential interface breaking change. Please note the following:

- `countUsed()` is deprecated in favor of `numInstances()` which reflects the meaning behind it
- `xAH::AlgorithmRegistry` is gone. The `Root/LinkDef.h` file has been correspondingly updated.
- `xAH::Algorithm` manages the entire thing in a static `std::map`
- All algorithms that inherit from `xAH::Algorithm` need to do something like
  ```
  JetSelector :: JetSelector () :
      Algorithm("JetSelector"),
          ...
        {
            // ...
        }
  ```

  which will tell `xAH::Algorithm` to automatically register by calling `xAH::Algorithm::registerInstance()` for us. The instance is unregistered from the map (it's reference-count decreases by one for the given class name) through `xAH::Algorithm::~Algorithm`
- `m_classname` is now renamed `m_className`

# The *ENTIRE* class has been documented.

### CODE REVIEW

**Comment by kratsg** [comment]
@mmilesi any updates? I'm going to merge this in 6 hours.

**Comment by mmilesi** [comment]
I am testing this now. Sorry but I got to finish some stuff first.

**Comment by kratsg** [comment]
@mmilesi this should include everything we've discussed now:

- handle sub-derived classes (`C : public B` and `B : public A`) by allowing you to pass in the custom class name through the parent's constructor
- fix for the instance counts by creating an `algInitialize()` function that gets called in `histInitialize()` downstream. It's still auto-registering, just needs the registration to be trigger from the algorithms themselves on worker nodes

@johnda102 can you test this too please? Thanks.

**Comment by johnda102** [comment]
sure.

Whats not clear to me is where the numInstances functionality gets used.

On Wed, Nov 25, 2015 at 4:04 AM, Giordon Stark <notifications@github.com>
wrote:

> @mmilesi <https://github.com/mmilesi> this should include everything
> we've discussed now:
>
>    - handle sub-derived classes (C : public B and B : public A) by
>    allowing you to pass in the custom class name through the parent's
>    constructor
>    - fix for the instance counts by creating an algInitialize() function
>    that gets called in histInitialize() downstream. It's still
>    auto-registering, just needs the registration to be trigger from the
>    algorithms themselves on worker nodes
>
> @johnda102 <https://github.com/johnda102> can you test this too please?
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/pull/373#issuecomment-159474122>
> .
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by kratsg** [comment]
It's used here: https://github.com/UCATLAS/xAODAnaHelpers/pull/373/files#diff-fdf2686fdb28afef2d9f9bfed6bacc1aR318 for example.

**Comment by kratsg** [comment]
This should add the rest of the logic that is missing. I did confirm that it counts the number of instances correctly on my end :) 

@johnda102 and @mmilesi should probably check it again.. but I'm going to go ahead and merge it.

**Pull request merged**
