### PR TITLE
Adding JetCharge

### PR DESCRIPTION
**Pull request by johnda102**

### CODE REVIEW

**Comment by kratsg** [comment]
@johnda102 what file are you looking at where jet charge isn't run for you? @mileswu should chime in but JSSU is run at the DF level at least to compute a lot of the substructure stuff for you.

**Comment by johnda102** [comment]
Is there a direct accessor for jet charge?
I was under the assumption one needed to use the JSSU.





On Tue, Mar 22, 2016 at 10:25 PM, Giordon Stark <notifications@github.com>
wrote:

> @johnda102 <https://github.com/johnda102> what file are you looking at
> where jet charge isn't run for you? @mileswu <https://github.com/mileswu>
> should chime in but JSSU is run at the DF level at least to compute a lot
> of the substructure stuff for you.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/pull/554#issuecomment-200036330>
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by kratsg** [comment]
```
http://atlas-computing.web.cern.ch/atlas-computing/links/nightlyDocDirectory/xAODJet/html/
xAOD::JetContainer
  |     xAOD::JetContainer* AntiKt10LCTopoJets
  |       |     Int_t &->btagging()
  |       |     UInt_t &->btagging.m_persIndex()
  |       |     UInt_t &->btagging.m_persKey()
  |       |     vector<ElementLink<DataVector<xAOD::IParticle> > > &->constituentLinks()
  |       |     vector<float> &->constituentWeights()
  |       |     float &->eta()
  |       |     float &->m()
  |       |     float &->phi()
  |       |     float &->pt()
  |       |     &->getAttribute<float>("ActiveArea")
  |       |     &->getAttribute<float>("ActiveArea4vec_eta")
  |       |     &->getAttribute<float>("ActiveArea4vec_m")
  |       |     &->getAttribute<float>("ActiveArea4vec_phi")
  |       |     &->getAttribute<float>("ActiveArea4vec_pt")
  |       |     &->getAttribute<int>("AlgorithmType")
  |       |     &->getAttribute<float>("Angularity")
  |       |     &->getAttribute<float>("Aplanarity")
  |       |     &->getAttribute<float>("AverageLArQF")
  |       |     &->getAttribute<float>("BchCorrCell")
  |       |     &->getAttribute<float>("CentroidR")
  |       |     &->getAttribute<float>("Charge")
```

It is a direct accessor... http://kratsg.github.io/xAODDumper/

More people should really be using my tool to see what attributes exist on these xAODs.

**Comment by johnda102** [comment]
OK,  then Im confused then b/c I asked miles and he said in needed to be recalculated.

**Comment by johnda102** [comment]
Does your dumper tool work on files over FAX ?

**Comment by gfacini** [comment]
This TWiki helps too:
https://twiki.cern.ch/twiki/bin/viewauth/AtlasProtected/Run2JetMoments

**Comment by kratsg** [comment]
If you change a lot of things about the jet, then you do need to recalculate the jet charge. Although it's not clear why you would even run the JSSU in the first place if you end up recalculating it later?

And you can pass in an xrootd path to process. It doesn't need to run over a full dataset, but just a partial.

**Comment by johnda102** [comment]
So doing both ways gives significant differences:

 static JetSubStructureUtils::Charge charge_calculator(1.0); //k is the exponent in the jet charge formula, defaults to 1.0]            
static SG::AuxElement::ConstAccessor<float> jetCharge ("Charge");
std::cout << "comp " << charge_calculator.result(*jet_itr) << " " << jetCharge(*jet_itr) << " diff " << charge_calculator.result(*jet_itr)-jetCharge(*jet_itr) << std::endl;

output:
comp 0.000907052 0.00209232 diff -0.00118527
comp 0.223929 0.478303 diff -0.254374
comp -0.169182 -0.303153 diff 0.13397
comp -0.067406 -0.094368 diff 0.026962
comp 0.223589 0.37765 diff -0.15406
comp 0.102378 0.172802 diff -0.0704242
comp 0.0638081 0.115285 diff -0.0514766
comp -0.133889 -0.375763 diff 0.241874
comp -0.0696212 -0.0938046 diff 0.0241834
comp 0.00311518 0.00517803 diff -0.00206285
comp -0.386909 -1.08744 diff 0.700534
comp 0.363366 0.489067 diff -0.125701
comp 0.128011 0.162952 diff -0.0349407
comp -1.3948 -1.9173 diff 0.522501
comp 0.0237571 0.0397437 diff -0.0159866
comp 0.01304 0.0185595 diff -0.00551952
comp -0.691568 -1.91083 diff 1.21926
comp -0.126397 -0.169331 diff 0.0429341
comp 0.112082 0.183399 diff -0.0713171
comp 0.197107 0.285844 diff -0.0887363

I think we need clarity from @mmilesi  here

**Comment by kratsg** [comment]
> I think we need clarity from @mmilesi here

You mean @mileswu?

**Comment by kratsg** [comment]
> static SG::AuxElement::ConstAccessor jetCharge ("Charge");
> std::cout << "comp " << charge_calculator.result(jet_itr) << " " << jetCharge(jet_itr) << " diff " << charge_calculator.result(jet_itr)-jetCharge(jet_itr) << std::endl;

Shouldn't that be

```
static SG::AuxElement::ConstAccessor<float> jetCharge("Charge");
```

also, you can do `jet->getAttribute<float>("Charge")` instead for a quick convenience.

**Comment by johnda102** [comment]
yes that was a problem with the comment not rendering, try agian 

im doing:
"""c++
static JetSubStructureUtils::Charge charge_calculator(1.0); //k is the exponent in the jet charge formula, defaults to 1.0]            
static SG::AuxElement::ConstAccessor<float> jetCharge ("Charge");
"""

**Comment by mswiatlo** [comment]
JetCharge is normalized by the pT of a jet: see equation 1 http://arxiv.org/pdf/1509.05190v1.pdf

So in principle yes, it should be recomputed once you have calibrated your jets.

Best,
Max

On Mar 22, 2016, at 4:59 PM, johnda102 <notifications@github.com<mailto:notifications@github.com>> wrote:


yes that was a problem with the comment not rendering, try agian

im doing:
"""c++
static JetSubStructureUtils::Charge charge_calculator(1.0); //k is the exponent in the jet charge formula, defaults to 1.0]

static SG::AuxElement::ConstAccessor jetCharge ("Charge");
"""

**Comment by johnda102** [comment]
ok so we accept the pull request I assume.

go ahead

On Tue, Mar 22, 2016 at 11:03 PM, Maximilan Swiatlowski <
notifications@github.com> wrote:

> JetCharge is normalized by the pT of a jet: see equation 1
> http://arxiv.org/pdf/1509.05190v1.pdf
>
> So in principle yes, it should be recomputed once you have calibrated your
> jets.
>
> Best,
> Max
>
> On Mar 22, 2016, at 4:59 PM, johnda102 <notifications@github.com<mailto:
> notifications@github.com>> wrote:
>
>
> yes that was a problem with the comment not rendering, try agian
>
> im doing:
> """c++
> static JetSubStructureUtils::Charge charge_calculator(1.0); //k is the
> exponent in the jet charge formula, defaults to 1.0]
>
> static SG::AuxElement::ConstAccessor jetCharge ("Charge");
> """
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub<
> https://github.com/UCATLAS/xAODAnaHelpers/pull/554#issuecomment-200050303>
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/pull/554#issuecomment-200051496>
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by mileswu** [comment]
The large-R jets do usually have jet charge computed during the derivation framework and stored as "Charge", but the small-R jets (which was what Patrick said he was using) I think do not, so for these you would need to compute it yourself with JSSU.

@mswiatlo is correct in that the last step of the calculation is dividing by the jet pT so in theory after calibration jet charge should be re-calculated (I suppose you could do this correction by doing charge*old_pt/new_pt). However, I don't expect that it would cause such large differences as @johnda102 sees in his example output. Are any of the ghost-associated tracks being slimmed out during the derivation as that might cause the large difference? Could you also print out jet pT to see if it is mostly the low-pT jets that have the large difference (as the calibration would have a larger effect here)?

**Comment by johnda102** [comment]
@mileswu we are indeed including low pt jets here (down to 25 GeV).

As the G.A. tracks are not available by default in a lot of derivations it
seems like the best thing to do would be to save as decorations:
   -  jet charge
   -  jet_pt used in jet charge calculation

This way the end user can correct the jet charge without needing the G.A.
tracks and without a costly loop over tracks even if they did have them.

Maybe this info is already there ? Is a reliable way to know what pt was
used in the original jet charge calculation ? If not,  who should we talk
to see if this is a possibility ?


On Wed, Mar 23, 2016 at 2:07 AM, Miles Wu <notifications@github.com> wrote:

> The large-R jets do usually have jet charge computed during the derivation
> framework and stored as "Charge", but the small-R jets (which was what
> Patrick said he was using) I think do not, so for these you would need to
> compute it yourself with JSSU.
>
> @mswiatlo <https://github.com/mswiatlo> is correct in that the last step
> of the calculation is dividing by the jet pT so in theory after calibration
> jet charge should be re-calculated (I suppose you could do this correction
> by doing charge*old_pt/new_pt). However, I don't expect that it would cause
> such large differences as @johnda102 <https://github.com/johnda102> sees
> in his example output. Are any of the ghost-associated tracks being slimmed
> out during the derivation as that might cause the large difference? Could
> you also print out jet pT to see if it is mostly the low-pT jets that have
> the large difference (as the calibration would have a larger effect here)?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/pull/554#issuecomment-200100388>
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by mswiatlo** [comment]
The derivation framework access jets almost entirely at the pileup subtracted scale (this is what is stored in Tier0, etc. at the moment). So in principle you could just multiply by the pt_calibrated / pt_pileup-subtracted and this would correct the moment for calibrations.

But Miles should confirm this makes sense of course!

**Comment by mileswu** [comment]
Just to clarify are we talking about large-R jets or small-R jets here? Patrick mentioned small-R but Giordon mentioned large-R.

Max's idea seems fine to me. All the four-momentum 'scales' should be stored on the xAOD::Jet and so you can access the pT used during the derivation framework and use that to correct it. I suppose you could check this idea on a few example jets.

**Comment by johnda102** [comment]
On Wed, Mar 23, 2016 at 6:04 PM, Miles Wu <notifications@github.com> wrote:

> Just to clarify are we talking about large-R jets or small-R jets here?
> Patrick mentioned small-R but Giordon mentioned large-R.
>

small-R jets


> Max's idea seems fine to me. All the four-momentum 'scales' should be
> stored on the xAOD::Jet and so you can access the pT used during the
> derivation framework and use that to correct it. I suppose you could check
> this idea on a few example jets.
>

ok so are we guaranteed that the same pt scale is used for all input
formats.
eg:
  xAOD
  DAOD




> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/pull/554#issuecomment-200443782>
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by gfacini** [comment]
Hi Max,

Why are you mentioning the derivation framework?

We are discussing small-R jets here and I thought
that these moments where default on all jets...well
this TWiki makes me think so

https://twiki.cern.ch/twiki/bin/viewauth/AtlasProtected/Run2JetMoments

and because of that, I thought they were calculated
straight away for the original xAOD itself.

Is this the wrong way to think about it?

Cheers,
Gabriel

**Comment by mswiatlo** [comment]
Hi all,

Sorry, I shouldn’t have mentioned the derivation framework. 

Jets at tier 0 are set to the pileup subtracted scale at this point in time. And the DF, or whatever else, doesn’t apply calibrations or anything. While some properties like JVT are recalculated in the DF, the 4-vector remains at the pileup subtracted scale always. 

So this should be consistent for xAOD and DxAOD yes.

Best,
Max

**Comment by johnda102** [comment]
ok great will update jet charge calculation accordingly.

(should update the jet moments twiki with this pro-tip)

On Wed, Mar 23, 2016 at 9:12 PM, Maximilan Swiatlowski <
notifications@github.com> wrote:

> Hi all,
>
> Sorry, I shouldn’t have mentioned the derivation framework.
>
> Jets at tier 0 are set to the pileup subtracted scale at this point in
> time. And the DF, or whatever else, doesn’t apply calibrations or anything.
> While some properties like JVT are recalculated in the DF, the 4-vector
> remains at the pileup subtracted scale always.
>
> So this should be consistent for xAOD and DxAOD yes.
>
> Best,
> Max
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/pull/554#issuecomment-200524404>
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by johnda102** [comment]
> So in principle you could just multiply by the pt_calibrated / pt_pileup-subtracted and this would correct the moment for calibrations.

I assume you mean multiply by  (pt_pileup-subtracted / pt_calibrated). right ?

**Comment by mswiatlo** [comment]
Yes, of course. Good catch.

**Comment by mileswu** [comment]
I just checked this: "Charge" attribute is saved in the primary xAOD during reconstruction for all jet collections, but many derivations slim it out for the small-R jets as it is not listed in the smart slimming filter (see for example https://svnweb.cern.ch/trac/atlasoff/browser/PhysicsAnalysis/DerivationFramework/DerivationFrameworkCore/trunk/python/AntiKt4LCTopoJetsCPContent.py). So you may still need to recalculate it if it's not in your favourite derivation flavour.

**Pull request merged**
