### PR TITLE
Feature: info switch python parsing

### PR DESCRIPTION
**Pull request by kratsg**
This provides a JSON file that will be checked for changes in Travis-CI builds for helping with info switch parsing. A later PR will parse this to check against a provided xAH configuration for specific info-switches.

This PR also moves a lot of the declarations back into the header file for info switches.

/cc @mattleblanc

### CODE REVIEW

**Comment by kkrizka** [comment]
Can you try to keep the initializations in the cpp file? This will cause everything to recompile anytime we try to tweak the code.

**Comment by kratsg** [comment]
> Can you try to keep the initializations in the cpp file? This will cause everything to recompile anytime we try to tweak the code.

Clang won't parse it. If you can figure out a way to get around the fact that clang only parses one file at a time...

**Comment by kkrizka** [comment]
By not using clang for this check. I would run the check at run time as I suggested in #1315 (user should run a test job before submitting to grid anyways...) or somehow force the info switches to initialize at submission time.

Putting code in the header also increases compile time. Any class that includes the `HelperFunctoins` (aka any class) will have to recompile all this code.

**Comment by kratsg** [comment]
> By not using clang for this check. I would run the check at run time as I suggested in #1315 (user should run a test job before submitting to grid anyways...) or somehow force the info switches to initialize at submission time.

I've tried to figure out a way to force info switches to initialize at submission time, but I cannot. So the easier way I've found is to do the parsing from within the xAH configuration instead -- but it won't be perfect since we can't handle all use-cases -- and this will only be used to check coverage.

> Putting code in the header also increases compile time. Any class that includes the `HelperFunctoins` (aka any class) will have to recompile all this code.

I've fixed this now by creating a tempfile that's the concatenated inputs of the header/source and feeding that into Clang's single-file parser.

**Comment by kratsg** [comment]
@kkrizka any updates? Should I merge this in?

**Comment by kkrizka** [comment]
Some things came up this week that I had to deal with urgently. But an alternative is on the way.

**Pull request closed without merging**
