### PR TITLE
Debugging Muons

### PR DESCRIPTION
**Pull request by johnda102**
@mmilesi  have a look ive made a few minor changes to the muons selection to support more than one instance with different quality cuts and to calibration to avoid a bunch of error print out

### CODE REVIEW

**Comment by mmilesi** [comment]
Hi @johnda102 

this looks good to me. I agree that the `ToolStore` retrieval should be removed if one wants to have multiple selectors with different configurations.

Just one question:

https://github.com/UCATLAS/xAODAnaHelpers/pull/367/files#diff-76bd3f85a73152f1f60bf2ddfa6266c8R306

is this b/c of derivations thinning out tracks for (I guess) very low pT muons? So far I never encountered crashes, so I thought the check on the existence of the track particle for a muon candidate was done internally by the calibration tool.

Marco

**Comment by johnda102** [comment]
On Sat, Nov 21, 2015 at 8:25 AM, Marco Milesi <notifications@github.com>
wrote:

> Hi @johnda102 <https://github.com/johnda102>
>
> this looks good to me. I agree that the ToolStore retrieval should be
> removed if one wants to have multiple selectors with different
> configurations.
>
> Just one question:
>
>
> https://github.com/UCATLAS/xAODAnaHelpers/pull/367/files#diff-76bd3f85a73152f1f60bf2ddfa6266c8R306
>
> is this b/c of derivations thinning out tracks for (I guess) very low pT
> muons? So far I never encountered crashes, so I thought the check on the
> existence of the track particle for a muon candidate was done internally by
> the calibration tool.
>

yes I think so.  I dont see any crashes either, but I see an error message
each time a muon without a track particle gets passed.  (Using EXOT8). When
running the ttbar MC they are very many messages.

john

> Marco
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/pull/367#issuecomment-158604021>
> .
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by mmilesi** [comment]
Hi @johnda102 ,

I had updated my comment with another question you probably missed :wink:  I copy it here:


> However, I think we should do something like this:
> 
> https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/JetSelector.cxx#L383
> 
> since I suspect it could be a potential issue to have multiple instances of the same CP tool with the same name on asg::toolStore. Maybe we could still drop the attempt to retrieve from ToolStore...
> 
> I will take care of fixing this also in the other selectors etc. in a different PR.

Marco

**Comment by johnda102** [comment]
yup missed it.

Yes that sounds good to me

On Sat, Nov 21, 2015 at 1:26 PM, Marco Milesi <notifications@github.com>
wrote:

> Hi @johnda102 <https://github.com/johnda102> ,
>
> I had updated my comment with another question you probably missed [image:
> :wink:] I copy it here:
>
> However, I think we should do something like this:
>
>
> https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/JetSelector.cxx#L383
>
> since I suspect it could be a potential issue to have multiple instances
> of the same CP tool with the same name on asg::toolStore. Maybe we could
> still drop the attempt to retrieve from ToolStore...
>
> I will take care of fixing this also in the other selectors etc. in a
> different PR.
>
> Marco
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UCATLAS/xAODAnaHelpers/pull/367#issuecomment-158634954>
> .
>



-- 
University of Chicago
http://hep.uchicago.edu/~johnda

**Comment by mmilesi** [comment]
Ok, it will be fixed in my upcoming PR!

**Pull request merged**
