### PR TITLE
Add trigger jet cleaning

### PR DESCRIPTION
**Pull request by kalderon**
Changes by @etolley to add HLT jet cleaning. Also change accessors from char to int.

### CODE REVIEW

**Comment by jbossios** [comment]
Wouldn't be better to add a specific string for jet trigger cleaning? Otherwise, now everybody gets that branch even for not trigger jets, and even in the cleanLight option which is meant to avoid having things which are mostly never used (like jet trigger cleaning).

**Comment by kalderon** [comment]
Jona you're quite right, and the char -> int caused other problems (it was needed for HLT jets, but breaks non-HLT jets). So I will close this for now, please don't merge, and will reopen when fixed

**Comment by kratsg** [comment]
@kalderon you can just mark as WIP.

**Comment by kalderon** [comment]
Emma's changes from ~ a month ago fix this

**Comment by kratsg** [comment]
All fixed?

**Comment by jbossios** [comment]
Wouldn't be better not to set branches that then are not filled?

**Comment by kratsg** [comment]
> Wouldn't be better not to set branches that then are not filled?

You would prefer the branches to stay fixed? Usually, the design pattern we do is to only include a branch if we intend to fill it. That at least indicates to the user that if the branch exists, it was filled in.

**Comment by jbossios** [comment]
I meant exactly what you said. If I'm not mistaken with this MR we would be creating branches than then are not filled.

**Comment by kalderon** [comment]
Yes, good point. I've tweaked things now so that there are no more "phantom" cleaning branches created (commit incoming).

**Comment by kratsg** [comment]
Looks good to me.

**Comment by jbossios** [comment]
Me too. Thank you!

**Pull request merged**
