### PR TITLE
adding VeryLoose electron wp

### PR DESCRIPTION
**Pull request by alexandertuna**
Adding the VeryLoose working point for electrons. This means adding VeryLoose to the ParticlePIDManager (fine) and setting VeryLoose to be the loosest available WP in ElectronSelector (does this fuck up anyone's day?). I think @mmilesi wrote most of these sections, so if he could sign off, that'd be great.

Sorry for replacing some of the tabs with spaces. I can't control myself.

### CODE REVIEW

**Comment by kratsg** [comment]
@alexandertuna I love spaces. Can you look at #604 quickly and see if you're conflicting somehow?

**Comment by alexandertuna** [comment]
@johnda102 and I are both editing ParticlePIDManager.h, but in different places. I'm not sure if git can handle it.

**Comment by alexandertuna** [comment]
Also, I clicked "Update branch" but I have no idea what that does. I felt pressured.

**Comment by kratsg** [comment]
@alexandertuna I can handle it if `git` can't. don't worry. Also the `update` branch was silly. It just meant you were based off an older version of the code and should have `git fetch && git rebase origin/master` before pushing your changes.

**Comment by alexandertuna** [comment]
Thanks @kratsg. My bad on the fetch & rebase. I must've done that before the xAH_run PR.

**Comment by kratsg** [comment]
Since this works on 2.4.8 -- I will merge this in first and then rebase #604 to push that ahead and things should be fixed there.

**Pull request merged**
