### PR TITLE
WIP: move btag decorator outside of systematics loop

### PR DESCRIPTION
**Pull request by lschaefer**

### CODE REVIEW

**Comment by kratsg** [comment]
@jdandoy I'm not sure this is correct, still. Shouldn't the systematic loop contain nominal?

**Comment by jdandoy** [comment]
Hi @kratsg ,

The systematic loop does contain the empty string signifying nominal already, but it is not yet setup to run on the "Nominal" string.  More work will be ongoing to add it.

**Comment by kratsg** [comment]
> The systematic loop does contain the empty string signifying nominal already, but it is not yet setup to run on the "Nominal" string. More work will be ongoing to add it.

In which case, moving the b-tagging out of it won't work as you'll still want to be able to decorate the systematic-varied jets differently, rather than b-tagging once.

**Comment by jdandoy** [comment]
Yes you're right, the systematics that alter the jet pt will need to have the b-tagging decision re-evaluated.  We'll put this back in while we update to HelperFunction's getListofSystematics

**Pull request merged**
