### PR TITLE
added all of the working points for electrons with a std::map

### PR DESCRIPTION
**Pull request by MihaMuskinja**

### CODE REVIEW

**Comment by kratsg** [comment]
go ahead

**Comment by mmilesi** [comment]
Hi @MihaMuskinja ,

did you test this on top of the changes for ElectronEfficiencyCorrector  I sent you, or is it independent from them?

**Comment by MihaMuskinja** [comment]
Hi @mmilesi ,

in principle it is independent from them, but I tested it on top of the ElectronEfficiencyCorrector changes. The code expects the new name convention. It should still work with the old ElectronEfficiencyCorrector, however, it wouldn't store any scale-factors to the output.

Best,
Miha

**Comment by mmilesi** [comment]
Ok thanks!

I will first submit a PR for my changes, and then merge yours.

Marco

**Comment by mmilesi** [comment]
Hi @MihaMuskinja 

can you try to do the following:

```
git fetch upstream
git rebase upstream/work/IsolationAndIDSF
```

and then (after fixing any conflict):

```
git push -f origin work/IsolationAndIDSF
```

?

**Comment by MihaMuskinja** [comment]
Hi @mmilesi ,

I did as you suggested. There were no conflicts I believe.

**Comment by MihaMuskinja** [comment]
Hi @mmilesi ,

however, I still have to add the possibility of no isolation to my changes.

**Comment by MihaMuskinja** [comment]
Dear @mmilesi ,

I get strange strings in case of no isolation working point:

 ```
Trigger ISOLATION wp: tronEfficiencyCorrection/2015_2016/rel20.7/ICHEP_June2016_v3/trigger/efficiencySF.DI_E_2015_e17_lhloose_2016_e17_lhloose.LooseAndBLayerLLH_d0z0_v11
 Trigger ID wp: LooseAndBLayerLLH
```

**Comment by MihaMuskinja** [comment]
Hi @mmilesi ,

sorry, I did not properly update the code with the new parsing functions `HelperFunctions::parse_wp`. It works fine now.

I updated my changes as well to allow for a working point with no isolation for trigger scale-factors.

noisotrigger


Best,
Miha

**Pull request merged**
