### PR TITLE
Fix for mssing nominal container in OverlapRemoval

### PR DESCRIPTION
**Pull request by mmilesi**
Hi @JamesSaxon,

please test this PR (just fetch the branch locally and test it with your configuration). If everything is fine for you, just go ahead and merge it :wink: 

Marco

### CODE REVIEW

**Comment by mmilesi** [comment]
@JamesSaxon

to fetch the branch on your local area:

```
git fetch origin
git checkout --track origin/FixNominalSysOverlapRemoval
```

After that, you can add commits to it! Once you're set, do:

```
git push -f origin FixNominalSysOverlapRemoval
```

and this PR will be automagically updated

**Comment by mmilesi** [comment]
Ok, I think I have seen where the problems stem from. I am making some changes now

**Comment by mmilesi** [comment]
This is strictly related to #287

**Comment by mmilesi** [comment]
Hi @JamesSaxon

do you think we can merge this? Did you have any chance to make a final test on it?

Cheers

Marco

**Comment by JamesSaxon** [comment]
Hi @mmilesi  -- 

This works as expected for me.  I continue to find it convoluted that _every_ downstream algorithm should take in three sets of systematics and figure out the overlapping set.  

To me a simple example of this is that if I run a single electron systematic (jets and muons nominal), then the nominal jet container no longer exists post OR.  So when I retrieve the jet syst vector from the selector tool, I have to check that muons and electrons have "nominal" defined.

And in principle I have to do that (or use a helper) for _every_ algorithm post overlap.  But, I think we both understand the sides of this at this point.  If anyone else has an opinion here, it would be great to chime in.

Thanks so much Marco, for doing all of the work on this.

Best -- 

Jamie

**Comment by mmilesi** [comment]
Hi @JamesSaxon ,

thanks for the comments, I definitely agree with you that there's plenty of room for improvement of the logic of the overlap removal machinery. For this reason, I'd encourage to make a new PR soon with updates on this!

For the time being, given this PR - although non optimal -is  fixing some pretty serious bugs, I'd go ahead and merge it. Do you agree?

Marco

**Comment by JamesSaxon** [comment]
Yep, sounds great!!

**Comment by mmilesi** [comment]
Merging this PR. This closes #287

**Pull request merged**
