### PR TITLE
Do not hardcode PRW scale factors

### PR DESCRIPTION
**Pull request by ntadej**
Do not hardcode PRW scale factors. These are defined in the tool and currently there is no reason to edit them by hand.

### CODE REVIEW

**Comment by ntadej** [comment]
Travis stalling on docker step again :)

**Comment by kratsg** [comment]
> Travis stalling on docker step again :)

restarted build. You should also have access to restart the builds as well on travis, I think, if you log-in with your github account.

**Comment by ntadej** [comment]
I don't think I have them. I guess I need to be a project member to be able to do it (I tried it before and I didn't see any button).

**Comment by kratsg** [comment]
I see, it's probably admin-only for right now.

**Comment by fscutti** [comment]
Hi @kratsg, can this be merged? It seems pretty urgent and I'm not able to merge myself.

**Pull request merged**
