### PR TITLE
xAH_run Condor AdditionsFixed problem with filelists and condor in xAH_run. Added option --op…

### PR DESCRIPTION
**Pull request by kkrizka**
Fixed problem with filelists and condor in xAH_run. Previously xAH_run assumed that all running on condor is with DQ2.

Added option --optCondorWait to submit to condor using the submit() command. This causes the code to wait until all jobs are finished and then merge all of the outputs automatically.

### CODE REVIEW

**Comment by kratsg** [comment]
Hi @kkrizka -- will this merge output by sample or ALL output?

**Comment by kkrizka** [comment]
By sample.

**Comment by kratsg** [comment]
Oh, awesome!

**Comment by kratsg** [comment]
The only other commend I have is you have the `needXRD` but then use `args.use_scanDQ2` and I can't see a logical difference in the script as it worked back then (note that a shared-fs condor doesn't want scanDQ2 automatically).

**Comment by kkrizka** [comment]
Previously xAH_run assumed that condor means you are running on a DQ2 sample (ie: called scanDQ2). However the input can also be list of ROOT files on an xrd server, listed in a filelist. The `needXRD` now checks if xrdclients are present (useful for DQ2 and filelists). Then `args.use_scanDQ2` runs scanDQ2 on if the input is from DQ2.

**Comment by kratsg** [comment]
> Previously xAH_run assumed that condor means you are running on a DQ2 sample (ie: called scanDQ2).

How do you see that? The old code was

```
   use_scanDQ2 = (args.use_scanDQ2)|(args.driver in ['prun', 'lsf'])
```

This now means if someone uses `prun`, the script doesn't automatically use `scanDQ2` but will require the user to add that option.

**Comment by kkrizka** [comment]
Ah right, I forogt also added 'condor' to the list of drivers for this check. 
Since the condor driver checks if all files can be opened before submission, I 
wanted to make sure xrd is setup properly.

After this change it reduced to what I described previously.

**Comment by kratsg** [comment]
Right, but you'll notice that you changed `use_scanDQ2` to `args.use_scanDQ2` so it won't automatically switch on with specific drivers.

**Pull request merged**
