### PR TITLE
Adding SCTError event cleaning cut for data

### PR DESCRIPTION
**Pull request by mmilesi**
See:

https://twiki.cern.ch/twiki/bin/view/AtlasProtected/PhysicsAnalysisWorkBookRel20CPRec#Event_cleaning

### CODE REVIEW

**Comment by johnda102** [comment]
Looks good

**Comment by urania277** [comment]
non-github question: what is this (apart from being in that page and saying 'new')? if you have any twikis or talks pointing to it, it'd be useful. Thanks!

**Comment by mmilesi** [comment]
Hi @urania277 ,

the only info I found is the following:

https://twiki.cern.ch/twiki/bin/viewauth/Atlas/DataPreparationCheckListForPhysicsAnalysis#Rejection_of_bad_corrupted_event

Marco

**Comment by urania277** [comment]
Thanks Marco! We got more info from the tracking conveners...apparently those are (some other) trackless events that originate from a transient problem in the SCT. It only affects a small fraction of the data but it's best to throw them away. 

-------------------------------------
Caterina Doglioni
Lund University, Fysikum
Division of Particle Physics
+46 (0) 46-22 27695
-------------------------------------

**Pull request merged**
