### PR TITLE
Jgeisen fat jet variables 2020 03 16

### PR DESCRIPTION
**Pull request by jgeisen**
Hi, I am performing an analysis on large-R jets with xAODAnaHelpers. I managed to add three additional variables that we have in our DAODs, but were previously not stored when writing those jets to a tree. Giordon asked me to merge these changes, as they might be interesting for other analysers.

### CODE REVIEW

**Comment by jgeisen** [comment]
Hi, sorry I forgot to add a description of this MR. I am performing an analysis on large-R jets with xAODAnaHelpers. I managed to add three additional variables that we have in our DAODs, but were previously not stored when writing those jets to a tree. Giordon asked me to merge these changes, as they might be interesting for other analysers.

**Comment by kratsg** [comment]
Will this crash if the variables are missing? Perhaps hiding it behind an extra flag is useful so people can turn on this extra stuff or not. I'm not sure here.

@jbossios ?

**Comment by jgeisen** [comment]
Hi, when I run on a test sample that doesn't contain these variables, it does not crash, because I use the accessors for ungrtrk500 and nChargedParticles which thus fill -999 if the variable is not present/available for whatever reason, while the function to get the EMFrac returns either -1 or 0 by default if something is not working. I just reconfirmed with a local test run on an older sample that this works.

**Comment by mswiatlo** [comment]
Hi,

Why did this add pvLocation without a default? This causes problems for users who now have to specify information they may not need to care about...

**Comment by kratsg** [comment]
> Why did this add pvLocation without a default? This causes problems for users who now have to specify information they may not need to care about...

Oh, that's  a good point... sorry for the oversight. I'll add in a default.

**Comment by jgeisen** [comment]
Hi,
indeed I forgot about this, sorry. Thanks for pointing it out. Also thanks Giordon for taking care of it!

**Pull request merged**
