### PR TITLE
Reduce variables

### PR DESCRIPTION
**Pull request by gfacini**

### CODE REVIEW

**Comment by kratsg** [comment]
@gfacini This will be a really confusing history. You're merging master into this branch and then merging this branch into master. Why didn't you rebase?

**Comment by gfacini** [comment]
hmm I guess I suck a git and thought I was rebasing....

**Comment by mmilesi** [comment]
Hi @kratsg , @gfacini 

is it ok to merge this?

**Comment by kratsg** [comment]
This is fine to merge.

**Pull request merged**
