### PR TITLE
xAH and submission of multiple datasets

### PR DESCRIPTION
**Pull request by kkrizka**
Implements submitting several datasets to the grid in a single JEDI task. Should address #837.
https://twiki.cern.ch/twiki/bin/viewauth/AtlasProtected/EventLoop#Processing_multiple_datasets_in

If you use `--singleTask` with `--inputList` option, the datasets in each filelist are grouped into one sample. The name of the input filelist is used as the sample name. Also `--singleTask` only works with rucio.

There are two hacks in this commit. 
* Adding `SampleGrid` does not seem to work in Python and throws the error below. Unclear why. I added a `xAH::addRucio` function that implements creating and adding the `SampleGrid` to `SampleHandler`.
> TypeError: vars() argument must have __dict__ attribute TypeError: an integer is required
* Adding `addRucio` to `HelperFunctions` does not seem to generate the dictionary correctly. Also unclear why. I added it to the `xAH` namespace instead.

Also removes `--inputDQ2`, since DQ2 does not exist anymore.

### CODE REVIEW

**Comment by kratsg** [comment]
Ok, I understand the changes being made here. The main question I have is what the use case for mapping N files in a file list to 1 sample is? Most people prefer to be able to have an output for each input and then merge them manually after some post-processing. I suspect that this isn't currently possible?

The hack is also curious and should be reported. I'm not 100% in favor of adding C++ code to make python code work... [especially because we'll have to go back and fix it when the python code eventually works again?]

**Comment by kkrizka** [comment]
My original plan was to use this to manage the submission of large number of datasets (ie: with mc16c, the number of datasets doubles...). The hope was that the `--addNthFieldOfInDSToLFN` prun option would also add the suffix to the output dataset for a file in addition to the output file name. For example, [user.kkrizka.Pythia8_dijet.fatjet.20180116-test-01_tree.root](https://bigpanda.cern.ch/datasetList/?containername=user.kkrizka.Pythia8_dijet.fatjet.20180116-test-01_tree.root/&jeditaskid=13022556) would become [user.kkrizka.Pythia8_dijet.fatjet.20180116-test-01_mc16_13TeV.361020.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ0W.tree.root](https://bigpanda.cern.ch/fileList/?datasetid=171528438). Sadly that is not the case, so I don't have a good use case for it anymore.

Unless @urania277 thinks that this meets her request in #837, I think I will remove this PR.

As for the bug, I've notified PATHelp a while ago.

**Comment by beojan** [comment]
As I stated in #837, this would be rather helpful to deal with missing period containers.

**Comment by kratsg** [comment]
> As I stated in #837, this would be rather helpful to deal with missing period containers.

Hi @beojan, you're welcome to try and get this working. This is in the `singleTask` branch in xAH so you can fork and submit a pull request if you get it working. I don't know if @kkrizka has time to work on this.

**Comment by ntadej** [comment]
Also, at this point, you should probably just request the period containers. They are just not created automatically.

**Comment by beojan** [comment]
I have, but @alexandertuna is waiting for the reprocessing to finish (EXOT8 didn't get reprocessed with the other derivations).

**Comment by beojan** [comment]
It seems to work just fine for my use case.

**Comment by kratsg** [comment]
@beojan if it works for you, we will merge it in.

**Comment by kkrizka** [comment]
If this way of combining tasks is OK, then this should be ready to merge.

**Pull request merged**
