### PR TITLE
Enable setting of map index in BJetEfficiencyCorrector

### PR DESCRIPTION
**Pull request by jbossios**
This adds the option (m_setMapIndex, false by defailt) to use the setMapIndex() function needed to properly apply MC/MC b-tagging SFs.

I added also the option of using a custom m_EfficiencyCalibration (non 'auto').

### CODE REVIEW

**Review by kratsg — APPROVED** [review]

**Comment by kratsg** [comment]
raedy to merge?

**Comment by jbossios** [comment]
> raedy to merge?

It is not, I plan to finish it later today.

**Comment by jbossios** [comment]
@kratsg If tests pass, it can be merged.

**Comment by jbossios** [comment]
In fact, wait a second (sorry) I will try to do another improvement.

**Pull request merged**
