### PR TITLE
GRL for 3runs of week 1

### PR DESCRIPTION
**Pull request by gfacini**

### CODE REVIEW

**Comment by gfacini** [comment]
unintentional changes to MET tools

**Comment by kratsg** [comment]
I don't understand this change.

**Comment by gfacini** [comment]
Which one?

**Comment by kratsg** [comment]
So you added a new GRL file, but also changed the MET stuff?

**Comment by gfacini** [comment]
That is why I cancelled the request and killed the branch - too many changes at once and I was not yet sure of the MET one.  I am ready to make MET changes but will probably screw up keeping the grl out...

**Comment by kratsg** [comment]
you can make a commit that removes the GRL via `git rm GRL file` and then rebase that commit with the other commit -- overall, it will look like you've never added the file in the first place.

Also, I noticed you're using TStrings in the MET Constructor?

**Comment by gfacini** [comment]
TStrings!!!   No that was not me =)  Jamie did it and you okayed the pull request.   Tisk Tisk.
I am in the middle of making some changes so Id wait a moment before killing all signs of
TStrings

Thanks for the commands =)

**Pull request closed without merging**
