### PR TITLE
Updates to automatic PRW configuration

### PR DESCRIPTION
**Pull request by kkrizka**
* Default 2017 MC is now mc16d
* Configs are now in `dev/SUSYTools/PRW_AUTOCONFIG_SIM/files` (new SUSYTools location)
* Differentiate between FS and AFII, decided from sample `metaString`
* Return `FAILURE` when a PRW config file is not found

### CODE REVIEW

**Comment by kratsg** [comment]
Is `SimulationFlavour` a thing automatically/correctly set? Or does the user now have to set it with something like `c.sample("410000", {"SimulationFlavor": "AFII"})`?

**Comment by kkrizka** [comment]
Sadly it has to be manually set. I use the following pattern.
```
c.sample('*_a875_*',SimulationFlavour='AFII')
c.sample('*_s3126_*',SimulationFlavour='FS')
```

**Comment by kkrizka** [comment]
Btw, the same `metaString` is used by the `JetCalibrator`. It would be nice to standardize AFII vs FS determination in all xAH algorithms. Via `c.sample` seems like a nice way.

**Comment by kratsg** [comment]
Hrmm, I suggest we update the error message, in the case of autoconfiguration, to explain what the user needs to do (add `SimulationFlavor` metaString) and point to the docs? https://xaodanahelpers.readthedocs.io/en/master/UsingUs.html#configuring-samples

**Comment by ecorrigan** [comment]
Hi! @kratsg 

I have actually just implemented something similar and was about to issue a PR, when I saw that this has already been done. Is there any reason it is still not merged? These changes are needed to run. 

Thanks!

Eric

**Comment by kpachal** [comment]
+1 :)

**Pull request merged**
