### PR TITLE
Add ability to disable counter branches

### PR DESCRIPTION
**Pull request by ntadej**
As some of us do not rely on the counter branches, it would be nice to add ability to remove them using `noCounter` switch.

### CODE REVIEW

**Comment by kkrizka** [comment]
Out of curiosity, what exactly do you gain by removing this branch?

**Comment by ntadej** [comment]
I gain some size, it might not be much, but you remove it ~40 times when doing systematics.

**Comment by kratsg** [comment]
I'm ok with this if @kkrizka is fine with it. But this is a "yet another configuration" which may or may not be useful...

**Comment by kkrizka** [comment]
I would agree with @kratsg here about this being "yet another configuration" which may or may not be useful".

**Comment by kkrizka** [comment]
@ntadej , do you have some statistics on how much you save on size when running with systematics?

**Comment by ntadej** [comment]
@kkrizka, I will try to do them. Until then, feel free to leave this open (I understand your opinion).

**Comment by ntadej** [comment]
I'm closing this for now. Will reopen if we will find it important again.

**Pull request closed without merging**
