### PR TITLE
Adding JetTruthLabelingTool

### PR DESCRIPTION
**Pull request by jrveatch**
This updates JetCalibrator to use JetTruthLabelingTool instead of SmoothedWZTagger for jet truth labeling.  This is only valid for AnalysisBase >= 21.2.114.

Closes https://github.com/UCATLAS/xAODAnaHelpers/issues/1438

### CODE REVIEW

**Comment by matthewfeickert** [comment]
Given the discussion on the mailing list, this PR will drop support for AB releases below `21.2.114`. I believe that the badges on https://xaodanahelpers.readthedocs.io/en/latest/ will get updated automatically.

**Comment by kratsg** [comment]
I'll wait for @kkrizka to comment with an LGTM but should be ok otherwise.



> Given the discussion on the mailing list, this PR will drop support for AB releases below `21.2.114`. I believe that the badges on https://xaodanahelpers.readthedocs.io/en/latest/ will get updated automatically thanks to [`docs/conf.py`](https://github.com/UCATLAS/xAODAnaHelpers/blob/734b5db001c7bdf534008c6e9fc9fdef2a21f53a/docs/conf.py#L124).

Yes. These are parsed from the github workflows.

**Comment by matthewfeickert** [comment]
Thanks for this PR, @jrveatch. :+1: It is really nice that you took time to write this up for us so quickly. :)

**Comment by jrveatch** [comment]
> Thanks for this PR, @jrveatch. 👍 It is really nice that you took time to write this up for us so quickly. :)

You're welcome. Implementing it also helped me uncover two minor issues with the JetTruthLabelingTool.

**Pull request merged**
