### PR TITLE
Supply substructure information when it is requested of the fat jet 

### PR DESCRIPTION
**Pull request by mattleblanc**
Should work fine -- I've tested things running on 2016 JETM8 data, at least.

### CODE REVIEW

**Comment by kratsg** [comment]
Go ahead

**Comment by kratsg** [comment]
@mattleblanc -- can you resolve the merge conflicts via a rebase please?

**Comment by mattleblanc** [comment]
✌️

**Comment by btamadio** [comment]
There will be a problem with systematics for tau32 and other substructure moments if using the HelpTreeBase as defined in this pull request.

Specifically, you have to first check if tau32 is available in the input jet, and use tau32 instead of the ratio of tau3/tau2. That's because if tau32 is already available, then tau3 and tau2 are not updated with systematic variations. A similar thing applies for ECF1,2,3. See the section "Substructure moment names" here:

https://twiki.cern.ch/twiki/bin/view/AtlasProtected/JetUncertainties2015Moriond2016LargeR

**Comment by kratsg** [comment]
@mattleblanc - can you update for this? (also resolve conflicts as well). Thanks!

**Comment by mattleblanc** [comment]
I'll fix this up shortly.

**Comment by mattleblanc** [comment]
Still haven't dealt with @btamadio's comment -- will do so shortly.

**Comment by mswiatlo** [comment]
#594 seems pretty related, might want to coordinate here?

**Pull request merged**
