### PR TITLE
Update recommendations for El/Mu @25ns in 2.3.28, and some bugfixes

### PR DESCRIPTION
**Pull request by mmilesi**
Please check the commits below to see all the changes made with this.

I tested it thoroughly as I used this to make my latest group 25ns ntuple production, and so far I din't spot any major flaws.

@johnda102 , can you please sign off this if you think it's ok? Fyi, this includes the change as in #263 
@JamesSaxon, could you also please have a look at this (I know you're a lepton aficionado too :smile: )

Cheers

Marco

### CODE REVIEW

**Comment by mmilesi** [comment]
Hi @kratsg 

I have rebased right before making this PR on top of 

commit 16e9d7f7205a7a37bf00875b02889189978cf1e6

and I managed to compile and run smoothly on 2.3.28 (the update of the travis file is part of the PR itself)

Do you know what's going on here?

**Comment by kratsg** [comment]
Hi @mmilesi, if you click the `Details` link

screenshot 2015-09-23 21 53 46

Then click `Console Output`

screenshot 2015-09-23 21 54 04

you can go ahead and [read through that](http://build.ci-connect.net:8080/job/xAH/job/main/158/console). The relevant error is

```
$ python xAODAnaHelpers/scripts/checkoutASGtags.py 2.3.28
  File "xAODAnaHelpers/scripts/checkoutASGtags.py", line 44
    '2.3.28': ["atlasoff/PhysicsAnalysis/JetTagging/JetTagPerformanceCalibration/CDIFiles/tags/CDIFiles-00-00-06",
           ^
SyntaxError: invalid syntax
```

**Comment by mmilesi** [comment]
A-ha! Thanks @kratsg , I overlooked that. The bug was a missing comma in checkoutASGtags.py, hence I did not see it. Good job Jenkins

**Comment by kratsg** [comment]
Jenkins sees all. Jenkins knows all. :hankey:

**Pull request merged**
