### PR TITLE
Copy data containers when applying electron and muon SF

### PR DESCRIPTION
**Pull request by ntadej**
Copy data containers when applying electron and muon SF. This way, we can use the same configuration for data and MC. If we copy containers for MC we should also do it for data.

### CODE REVIEW

**Comment by kratsg** [comment]
Why do you need a deep copy here? Wouldn't a shallow copy work?

**Comment by ntadej** [comment]
Oh, I haven't thought of that ... it's actually an old commit I wanted to submit upstream. I will investigate and update this PR.

**Comment by ntadej** [comment]
I now just make a new `ConstDataVector` and copy pointers to objects there. I think this is the cleanest option.

**Comment by ntadej** [comment]
I think this is not needed anymore.

**Pull request closed without merging**
