### PR TITLE
adding d0 decorator

### PR DESCRIPTION
**Pull request by alexandertuna**
For convenience downstream.

### CODE REVIEW

**Comment by kratsg** [comment]
@alexandertuna -- just so I'm clear... Why isn't

```
electron->trackParticle()->d0()
```

convenient enough?

**Comment by alexandertuna** [comment]
Hm, that looks pretty convenient. Gimme a sec.

**Comment by alexandertuna** [comment]
Good call, I'm an idiot. Can we kill this PR?

**Comment by kratsg** [comment]
💀 killed

**Pull request closed without merging**
