### PR TITLE
Update MuonCalibrator with the latest recommendations

### PR DESCRIPTION
**Pull request by ntadej**
This updates muon calibrator to latest recommendations. As far as I know it requires AB 21.2.19.

### CODE REVIEW

**Comment by kratsg** [comment]
> As far as I know it requires AB 21.2.19.

Then update the .travis.yml to account for those versions?

**Comment by ntadej** [comment]
@kratsg, should I keep the old versions there or bump everything to 21.2.19?

**Comment by kratsg** [comment]
> @kratsg, should I keep the old versions there or bump everything to 21.2.19?

You can see if it works in the old version.. but we probably just need to bump entirely, unfortunately. There's no way to support old releases and new releases at the same time.

**Comment by ntadej** [comment]
I know that `Data17` Year string only works since 21.2.19 so I guess yes, everything should be bumped. Unfortunately Docker images for this release are not available yet so I will wait until they are available.

**Comment by kratsg** [comment]
@lukasheinrich - when do you expect 21.2.19 docker images to come out for Base and Top releases?

**Comment by kratsg** [comment]
@ntadej new docker images should be coming out in a few hours for 21.2.19.

**Comment by kratsg** [comment]
images are up @ntadej

**Comment by ntadej** [comment]
Bumped the release. Sorry for the delay.

**Comment by kratsg** [comment]
@ntadej remove analysistop for now -- it's not getting built.

**Comment by ntadej** [comment]
Finally, this seems to be green :)

**Pull request merged**
