### PR TITLE
Revert "Add hlt jets"

### PR DESCRIPTION
**Pull request by jdandoy**
Reverts UCATLAS/xAODAnaHelpers#343

@johnda102  @kratsg This update breaks the trunk for standard ("jet") running.  No jet_pt is saved to the TTree output with this commit.

### CODE REVIEW

**Comment by johnda102** [comment]
This commit doesnt touch those files.
I guess its either an earlier problem or a later one.  
Ill what things look like from teh multijet side

**Comment by jdandoy** [comment]
Seems to work fine for John, but caused Dijet errors.  Will investigate this further from my side soon, and check with John before any action is taken.

**Comment by kratsg** [comment]
Hi @jdandoy -- before we start reverting, can you do the following?

```
git reset --hard dccd2af2
```

and see if it still works. (You will need an `rc clean` since it removes the header files). I'm also confused about why `jet_pt` seems missing since I don't see any of John's changes touching it.

**Comment by mmilesi** [comment]
@johnda, @jdandoy 

I am also observing something like what Jeff says when looking at master. I am looking into this as well

**Comment by kratsg** [comment]
Oh you know what? It might be related to the change in #342 -- but that only makes things tighter while preserving backwards compatibility. My next question would be -- what is your detail string when trying to do the kinematics?

**Comment by mmilesi** [comment]
This is what I am using:

"kinematic energy flavorTag sfFTagFix77 truth"
and atm only the branches corresponding to:

"energy flavorTag"

gets dumped

**Comment by kratsg** [comment]
Closing this because this should have been filed as an issue and the revert will not change or fix anything.

**Comment by jdandoy** [comment]
Hi @mmilesi,

Did you try running with commit 2706ff921e (right before this one?).  I went back one commit and found everything to work properly.

**Pull request closed without merging**
