### PR TITLE
Adding TightBad to the event information.

### PR DESCRIPTION
**Pull request by russbate42**

### CODE REVIEW

**Comment by mdhank** [comment]
Hi @russbate42 ,

Is this implementing the changes in this athena [MR](https://gitlab.cern.ch/atlas/athena/-/merge_requests/69006#2b21f0f9986a2b319b78e1be13fa433681362d3d)?  If so, we should wait until that is finalized to merge this PR.

I also wanted to check if there are any corresponding changes that should be made to our cleaning cuts. Currently, we apply the "DFCommonJets_eventClean_LooseBad" cut if the jet cleaning flag is set, see [BasicEventSelection.cxx#L919](https://github.com/UCATLAS/xAODAnaHelpers/blob/main/Root/BasicEventSelection.cxx#L919). Is this still the recommended default? Should the code be changed to allow a choice between no jet cleaning, loose, and tight?

Best,
Michael

**Comment by mswiatlo** [comment]
Mi @mdhank -- I'll let Russell answer the detailed questions but yes, this is meant to implement that MR in atlas/Athena, so it should go first!

**Comment by mdhank** [comment]
Hi @russbate42 ,

I wanted to follow-up on this- it looked like the corresponding Athena MR was merged. I think the only outstanding point is if we should change how we apply the jet cleaning.

Best,
Michael

**Comment by tofitsch** [comment]
Hi @mdhank , @russbate42 , LooseBad should stay the default for cleaning also in Run 3 (confirmed by Fabrice). The MR should be complete then. Can be merged.

**Pull request merged**
