### PR TITLE
fix for JetCalibration, minor change to downloader

### PR DESCRIPTION
**Pull request by johnda102**

### CODE REVIEW

**Comment by gfacini** [comment]
How does that fix the problem?  Isn't the default value for m_systName already ""?

**Comment by gfacini** [comment]
How does that fix the problem? Isn't "" already the defualt value of m_systName?

**Comment by johnda102** [comment]
No. The m_systName gets written in the config script with setConfig method of the base class. 
This happens after the constructor, but before the config method.

Without this change we iniit systName to "", then set it, then set it back to "" .

**Comment by kratsg** [comment]
I agree. :+1: Good catch John!

**Comment by kratsg** [comment]
This closes #236

**Pull request merged**
