### PR TITLE
Clean up old DC14 ElectronIsolationTool

### LINKED ISSUE #156: Get rid of ElectronIsolationSelectionTool across the board
Old shit from DC14 that needs to get flushed away

### PR DESCRIPTION
**Pull request by mmilesi**
Clean the old shit out. Resolves #156 .

### CODE REVIEW

**Comment by mmilesi** [comment]
@jdandoy

**Comment by mmilesi** [comment]
@kratsg can you please check what went wrong with the xAH-bot? It didn't start testing, so I went ahead and merged. Then I got the above message...

**Comment by kratsg** [comment]
Click the 'x' and click console output: http://build.ci-connect.net:8080/job/xAH/job/main/28/console

It will always start testing. I wouldn't merge until you hear from it to be honest.

**Comment by kratsg** [comment]
```
RootCore: Error package IsolationSelection not known, required by xAODAnaHelpers
```

**Comment by kratsg** [comment]
What AnalysisBase did you run this on? Chances are it doesn't see it in 2.3.14 -- so you should edit the `.travis.yml` file to make it test correctly again or update `python checkoutASGtags.py` to include it?

**Comment by mmilesi** [comment]
2.3.16 dude

**Pull request merged**
