### PR TITLE
ExpandPathName is no more

### LINKED ISSUE #776: Switch to new pathresolver
```
#include "PathResolver/PathResolver.h"
...
const std::string fileName = PathResolverFindCalibFile( "MyLoop/file.root" );
```

### PR DESCRIPTION
**Pull request by kratsg**
Closes #776.

### CODE REVIEW

**Comment by jdandoy** [comment]
@kratsg PathResolver does not seem to work in RootCore (2.4.31), as DATAPATH is not being set.  Maybe we need a workaround to use gSystem->ExpandPathName() when in 2.4.X?

**Comment by kratsg** [comment]
Use CalibFile, not DataFile

Giordon

**Comment by kratsg** [comment]
Also, the expandpathname isn't a workaround as the paths you pass in differ between PathResolver and ExpandPathName. Can you file a JIRA bug report or ask on PAThelp?

**Comment by jdandoy** [comment]
Okay CalibFile seems to work in both 2.4 and 2.6 (it's actually for the GRL xml path in BasicEventSelection), is there any reason to use DataFile instead of CalibFile there?  In fact, what's the difference between the two, does DataFile only correspond to atlas_install_data? 

Given CalibFile works fine with different paths in 2.4, I don't think there's a problem.

**Pull request merged**
