### PR TITLE
Protect JVFCorrName for r20.7

### PR DESCRIPTION
**Pull request by jdandoy**
Solves #946. The JVT Update tool accesses aux data with a different name between r20.7 and r21.  Unfortunately many mc16a samples have the old name, so a new property "JVFCorrName" was added to the tool to specify the name.  This property is only available in the r21 JetMomentTools tag, and after discussions with the experts it would be inconvenient to update the r20.7 tag to include it, especially given that no r20.7 samples have the r21 name.   I've therefore edited the logic so JVFCorrName will only be set if m_JvtAuxName is not empty, keeping backwards compatibility.

### CODE REVIEW

**Comment by kratsg** [comment]
@jdandoy Can you explain the name of the variable `m_JvtAuxName`? Is "Aux" for "Auxiliary" or something else? Otherwise, I like this fix.

**Comment by jdandoy** [comment]
Hi @kratsg,
You're correct, the string reflects the name of the auxdata variable.  I'm open to suggestions for a different name.

Jenkin's failed, but the console output suggests an issue with Jenkins?  Can you check this?

**Comment by kratsg** [comment]
Connect is down for upgrades

**Comment by kratsg** [comment]
go ahead

**Pull request merged**
