### PR TITLE
add jet scales to tree

### PR DESCRIPTION
**Pull request by gfacini**

### CODE REVIEW

**Comment by kratsg** [comment]
retest this please

**Comment by kratsg** [comment]
It looks like it's on 2.3.14, someone updated the travis file.

**Comment by kratsg** [comment]
retest this please

**Comment by gfacini** [comment]
what the what it compiles locally

**Comment by kratsg** [comment]
@gfacini The .travis.yml file specifies how to test it.

**Comment by kratsg** [comment]
I've rebased it for you:

```
git clone UCATLAS/xAODAnaHelpers
cd xAODAnaHelpers
git checkout JetScales
git rebase origin/master
git push -f
```

**Comment by gfacini** [comment]
thanks!

**Comment by kratsg** [comment]
Fun fact: if you had tried to merge it in without rebasing, you'd probably overwrite some changes made. ;) :gun:

**Pull request merged**
