### PR TITLE
Cutflowall

### PR DESCRIPTION
**Pull request by kkrizka**
Same as #1226, but with histogram creation moved back to `initialize()`. The call to `isMC()` now works.

### CODE REVIEW

**Comment by vpascuzz** [comment]
This addresses the following?
```
BasicEventSelect         INFO    Calling histInitialize
BasicEventSelection.Ba...INFO    Setting up histograms
BasicEventSelection.Ba...ERROR   in retrieve<xAOD::EventInfo_v1>(EventInfo): Both TEvent and TStore objects are null. Cannot retrieve anything.
/afs/cern.ch/user/v/vpascuzz/work/private/analysis/lxqq/code/DijetFramework_r21/source/DijetFramework/xAODAnaHelpers/Root/Algorithm.cxx:65:exception: Could not retrieve eventInfo container (EventInfo) for isMC() check.
```

**Comment by vpascuzz** [comment]
Yes -- thanks.

**Comment by kratsg** [comment]
Yes, it does. See #1226.

**Comment by fscutti** [comment]
Hi guys (@kkrizka @kratsg ),
I am getting a segfault after this merge. This is the full [stacktrace](https://www.dropbox.com/s/ymvne163bhebnp1/debug.txt?dl=0). I'm using 21.2.39 on a SUSY11. I did not investigate much but the segfault comes from BasicEventSelection. You might want to have a look at it.

Cheers,
Federico

**Pull request merged**
