### PR TITLE
Implement largeR truth-labelling in JetCalibrator for systematics.

### PR DESCRIPTION
**Pull request by kkrizka**
The latest JetUncertainties tool requires the largeR jets to be truth-labelled. This PR adds the functionality using the SmoothedWZTaggers tool ([following the recommendation](https://twiki.cern.ch/twiki/bin/view/AtlasProtected/JetUncertaintiesRel21Summer2019LargeR#Truth_labelling_via_BoostedJetTa)).

Tagging the resisdent largeR jet expert for cross-check. @mattleblanc 

Marking as WIP until my grid run with this finishes.

### CODE REVIEW

**Comment by balunas** [comment]
It's been over a month, any word on this? Is it still WIP? I was about to make a PR for this myself, but then I saw it was already started here.

**Comment by kkrizka** [comment]
Hey @balunas,

I ran into an unrelated problem with jet systematics that prevented me from checking the results. The number of NPs increases considerably with the new recommendations, meaning many more TTrees being written out by xAH. Most of my jobs have been crashing due to running out of memory, since each TTree allocates a considerable buffer.

But in principle, I think PR should be correct. I've pushed a few more changes that deal with an API change in the latest release.

--
Karol Krizka

**Comment by balunas** [comment]
Alright, thanks, just wanted to make sure this hadn't been forgotten. Let me know if you want a hand with anything, otherwise I'm happy to just wait till you've got it sorted out (this isn't super urgent for us).

-Bill

**Comment by balunas** [comment]
Just pinging this thread again - If it's actually ready to go in, can we remove the WIP tag?

**Comment by mswiatlo** [comment]
@kkrizka do you need any help validating this, or is it good to go? Thanks!

**Comment by kkrizka** [comment]
Hi,

No news on this from me. If you could validate the output, it would be great.

Also I think a small fix is needed for the latest release as the truth tag decoration name is no longer an argument.

--
Karol Krizka

**Comment by kratsg** [comment]
@kkrizka , if so - can you unWIP it?

**Comment by kkrizka** [comment]
Go ahead and merge it.

Disclaimer: The code runs without crashing. But I don't guarantee that the results make sense.

**Pull request merged**
