### PR TITLE
Adding b tag details to help tree base

### PR DESCRIPTION
**Pull request by johnda102**

### CODE REVIEW

**Comment by johnda102** [comment]
This build seems stuck.  How do we restart ?

**Comment by kratsg** [comment]
I've pinged Lincoln. Connect is not working again from what I can tell.

**Comment by johnda102** [comment]
ok cool.  So I guess nothing I can do on my side ?

**Comment by kratsg** [comment]
screenshot 2016-06-23 10 10 13

**Comment by robrwg** [comment]
Which service in ATLAS Connect is down?  login? condor?

**Comment by kratsg** [comment]
@robrwg -- ATLAS Connect Slave (http://build.ci-connect.net:8080/)

**Pull request merged**
