### PR TITLE
Major changes to Muon and Electron algos to work in 2.4 release

### PR DESCRIPTION
**Pull request by mmilesi**
1. Use common Trigger Matching Tool for electrons and muons, plus some bug fixes.
2. Revert to using CP tool pointers instead of AnaToolHandles in MuonEfficiencyCorrector until Nils fixes the issues w/ re-using the same tool with different ATHs.

This comes with quite some delay, apologies!

See commits for more details.

### CODE REVIEW

**Comment by kratsg** [comment]
The only thing that seems worrisome to me is commit 727a247 . Maybe @will-cern knows what's up here.

**Comment by mmilesi** [comment]
Hi Giordon,

can you please argument on what's wrong with that commit?

**Comment by kratsg** [comment]
Well, we're moving away from AnaToolHandle which is not what I was hoping (if you look at #617 ) -- we should move closer to trying to get differences between RootCore and Athena squashed.

**Comment by mmilesi** [comment]
Unfortunately this AnaToolHandle business is still not completely under control of ASG.
Specifically, if you look at the "Issues retrieving AnaToolHandle configured in separate class
" thread on PATHelp, I am trying to figure out with Nils why some unexpected behaviour appears  when trying to configure ATHs with the same tool name.
He's currently debugging, hope to have more updates soon.

For now, since people (e.g. Federico from Melbourne) need to progress, I had to revert back to the "old" setup, at least where needed.

Marco

**Comment by mmilesi** [comment]
Thanks for merging @kratsg 

FYI, Nils has made a major rewriting of the AnaToolHandle class that I could test in the 2.5.X nightlies.
It seems to finally work as it should!

He told me the ASG plan is now to backport this change also in the latest 2.4 releases, so we could hopefully make the switch to ATH everywhere soon. This should be discussed at the next ASG meetings.

Marco

**Comment by jdandoy** [comment]
Hey @mmilesi ,

Was this change implements, and can we revert back to using AnaToolHandles here?

**Comment by kratsg** [comment]
The change was implemented. We should revert back entirely as of 2.4.20.

**Pull request merged**
