### PR TITLE
add travis

### PR DESCRIPTION
**Pull request by kratsg**
this should get automatically tested

### CODE REVIEW

**Comment by kratsg** [comment]
The main reason this one failed is because we need to be able to checkout the packages which the Jenkins user can't do automatically. I will retest this when I clear this up with Lincoln.

**Comment by kratsg** [comment]
retest this please

**Comment by kratsg** [comment]
retest this please

**Comment by kratsg** [comment]
retest this please

**Comment by ndawe** [comment]
:beers:

**Pull request merged**
