### PR TITLE
Fix Jet Calibrator Systematics Handling 

### PR DESCRIPTION
**Pull request by btuan**
Hi All,

Just a few changes to fix the jet calibration step.
* JetCalibrator
  * Call `HelperFunctions::getListofSystematics()` like the other calibrators do.
  * Run nominal if `m_systName` is empty. If configured to be `None` or a specific systematic, do not run nominal.
  * Improve guards against duplicating nominal case.
  * **N.B. `outputAlgo` configuration changed to `outputAlgoSystNames` for uniformity. May break prior analyses if config file is not changed accordingly.**
* Other Changes
  * Add 25ns GRL to the `checkoutASGtags.py` script.

This addresses issues #236 and #237; is relevant to discussion in PR #238.

Best,

Brian

### CODE REVIEW

**Comment by kratsg** [comment]
@mswiatlo - can you sign off on this?

**Comment by mswiatlo** [comment]
Will look at this tomorrow

**Comment by mmilesi** [comment]
Hi @btuan ,

it looks okay to me. Only a question: what's the point of having a `None` systematic value?
Shouldn't it be a redundancy for the nominal case?

Marco

**Comment by btuan** [comment]
Hi @mmilesi ,

It can be easily implemented as a redundancy for the nominal case, but at present the `None` case is not being specifically handled. I think that this is likely a non-issue, since the config file recommends passing an empty string to the `OutputAlgoSystNames` parameter when running nominal only.

Best,
Brian

**Comment by mmilesi** [comment]
Hi @btuan,

yes, I agree with you. Personally, I'd eliminate `None` as a possible option as there's no need to have it, but it's certianly harmless to keep it around for now. Up to you.

For me, this can be merged, so...go ahead after you have changed that little thing (if you plan to)

**Comment by mswiatlo** [comment]
(Just to confirm: this did look good to me. Thanks!)

**Pull request merged**
