### PR TITLE
[WIP] R22

### PR DESCRIPTION
**Pull request by lukasheinrich**
This is a WIP branch for R22 xAH.

It complies cleanly on R22 but especially Jet/MET stuff is largely taken out. Tagging @jbossios @mattleblanc @balunas  @kratsg. Any ideas how to manage this transition? Keep a permanent R22 branch? Integrating a joint R21/R22 via ifdefs seems a little cumbersome (or one branches of R21 and switches master to R22)

### CODE REVIEW

**Comment by lukasheinrich** [comment]
maybe also interesting to @mswiatlo

**Comment by lukasheinrich** [comment]
ping! would be good to discuss how to move forward with this. I don't think a unified r22/r21 branch is going to be possible

**Comment by jbossios** [comment]
IMHO I would keep a R22 branch for now, it needs still a lot of work anyway, and cherry-pick commits made to master.

**Comment by jbossios** [comment]
@kratsg Could you please create a new branch (e.g. R22), so Lukas can merge this into that one. I will need to make some changes and I think it would be better to merge things into a branch in this repo than keeping things updated in a forked repo. What do you think?

**Pull request merged**
