### PR TITLE
store fat jets 4-momenta

### PR DESCRIPTION
**Pull request by francescorubbo**
Store fat jets 4-momenta as for jets (switch `kinematics`)
Will add additional branches (e.g. substructure) before merging.

### CODE REVIEW

**Comment by mmilesi** [comment]
Ciao @francescorubbo ,

looks good. Do you want me to wait for you to add new stuff to this PR before merging?

**Comment by francescorubbo** [comment]
Ciao @mmilesi ,

Yes, please. I expect to be done sometime tonight.

**Comment by mmilesi** [comment]
:+1:

**Comment by francescorubbo** [comment]
Good to merge. Thanks!

**Comment by kratsg** [comment]
This looks great. Thanks @mmilesi for merging and @francescorubbo for putting the changes in :) Hope it wasn't too painful.

**Comment by gfacini** [comment]
Awesome!! We have so much information include for the jets and not much for the fat jets....I wonder if there is a way of avoiding duplication of the code for the moments in common.  If one wants to write out only fat jet quantities then you can just FillJet( fatJets ) and FillFatJets( fatJets ) but if you want fat jets and non-fat jets in the same tree then to have the same moments, code might be duplicated.  Any clever solutions?

**Comment by kratsg** [comment]
@gfacini I have to think hard about it. I do have a clever solution that you'll like, but we should discuss this in gchat (it's a little lengthy).

**Pull request merged**
