### PR TITLE
Add possibility to use continuous b-tagging

### PR DESCRIPTION
**Pull request by jbossios**
Implementation based on the following official example:
https://gitlab.cern.ch/atlas/athena/blob/21.2/PhysicsAnalysis/JetTagging/JetTagPerformanceCalibration/xAODBTaggingEfficiency/util/BTaggingSelectionToolTester.cxx

### CODE REVIEW

**Comment by jbossios** [comment]
More info:
When using the "Continuous" working point, jets are decorated with the tagWeight and quantile. Nothing is changed when not using that working point.

**Comment by jbossios** [comment]
@kratsg Would be possible to merge this soon?

**Comment by jbossios** [comment]
I pushed a new commit fixing the order of bins in the cutflow histogram.

**Comment by kratsg** [comment]
> Don't merge this yet please. I have to make a small change.

As long as it's marked WIP, it won't be merged.

**Comment by jbossios** [comment]
@kratsg  It's ready to be merged now. Thanks!

**Pull request merged**
